---
logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
        security: DEBUG

spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://d613386ca6473479953e82bee5b2cff3@o4506718006083584.ingest.sentry.io/4506720157368320
  traces-sample-rate: 1.0