DELETE if EXISTS users;

CREATE TABLE users(
id SERIAL PRIMARY KEY,
firstName VARCHAR(255) NOT NULL,
lastName VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
createdAt TIMESTAMP,
updatedAt TIMESTAMP
);

-- NEED TO REMIND MYSELF HOW TO CREATE INTERNAL & EXTERNAL URL ADRESSES